name: Liquibase Rollback

on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Number of changes to rollback'
        type: number
        required: false
        default: 1
      force:
        description: 'Force execution'
        type: boolean
        required: false
        default: false

jobs:
  rollback-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Liquibase Rollback
        uses: liquibase-github-actions/rollback-count@v4.31.0
        with:
          changelogFile: liquibase/changelog/master.yml
          url: ${{ secrets.DB_URL }}
          username: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          driver: org.postgresql.Driver
          count: ${{ inputs.count }}