name: Liquibase Status

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'liquibase/**'
  workflow_dispatch:

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Liquibase Status Check
        uses: liquibase-github-actions/status@v4.31.0
        with:
          changelogFile: liquibase/changelog/master.yml
          url: ${{ secrets.DB_URL }}
          username: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          driver: org.postgresql.Driver
          verbose: true